source 'http://rubygems.org'

gem "rake", "~> 12.2"
gem "sinatra", "~> 2.0"
gem "sinatra-reloader", "~> 1.0"
gem "sinatra-activerecord", "~> 2.0"
gem "thin", "~> 1.7"
gem "geokit", "~> 1.11"
gem "builder", "~> 3.2"
gem "json", "~> 2.1"
gem "bcrypt", "~> 3.1"
gem "haml", "~> 5.0"
gem "sqlite3", "~> 1.3"
gem "mysql2", "~> 0.4.9"
gem "standalone_migrations", "~> 5.2"
